name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true  # Important to search for submodules
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build with Maven
        #run: mvn -B package --file pom.xml
		
      - name: Checkout repository
      
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: List files in current directory
        run: ls -la

      - name: Find and change to directory containing pom.xml
        run: |
          if [ -f "pom.xml" ]; then
            echo "Found pom.xml in root"
          elif [ -f "qa-challenge-master-set-challenge-unittests/set-challenge/unittests/netsim-feedzai/pom.xml" ]; then
            cd qa-challenge-master-set-challenge-unittests/set-challenge/unittests/netsim-feedzai
            echo "Found pom.xml in submodule"
          else
            echo "pom.xml not found" && exit 1

          ls -la

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=edimilsonestevam_qa-challenge-master-set-challenge-unittests
